# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate"]

# Permalinks
permalink:        pretty

# Setup
title:            "Sandy's Blog"
tagline:          'Single Page Application, Docker, Open Source...'
description:      'Ideas and thoughts'
url:              http://192.168.99.100:4000
baseurl:          /
avator:           /public/1374235_10151775570044965_766769785_n.jpg
intromessage:     "I am Sandy CHAN, 10+ yr experience front to  back full stack software developer focusing on enterprise software. I am interested in single page application, docker, cloud foundry, cloud related technologies"
disqusforumshortname:  "sandydy"
googleanalytics:  "UA-79163484-1"

author:           'Sandy CHAN'
name:           'Sandy CHAN'

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/sandydy/sandydy.github.io
  
twitter_username    : SandydyChan
github_username     : sandydy
facebook_username   : sandydy.chan
linkedin_username   : sandy-chan-053a70a4
gitlab_username     : sandydy